name := "daskvsspark-udafs"
version := "0.0.1"
scalaVersion := "2.11.8"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.1.0"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.1.0"
libraryDependencies += "org.apache.spark" %% "spark-hive" % "2.0.0" % "test"
libraryDependencies += "com.holdenkarau" %% "spark-testing-base" % "2.0.0_0.4.4" % "test"
